services:


  postgres:    
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5467:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: 
      unless-stopped


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HOSTNAME: 127.0.0.1
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: edge

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true



      KC_HTTP_ENABLED: "true"

    # volumes:
    #   - ./keycloak-themes:/opt/keycloak/themes
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped





  mailhog:
    depends_on:
      - keycloak
    image: mailhog/mailhog
    container_name: keycloak_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped




  timescaledb:
    image: timescale/timescaledb:latest-pg16 
    container_name: timescaledb
    environment:
      - POSTGRES_USER=${TIMESCALE_USER}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD}
      - POSTGRES_DB=${TIMESCALE_DATABASE}
    ports: 
      - "5468:5432"
    volumes: 
      - timescale_data:/var/lib/postgresql/data 
      - ./init-timescaledb:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALE_USER} -d ${TIMESCALE_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: 
      unless-stopped
  

  frcm-api:
    build: .
    container_name: frcm-api
    ports:
      - "6767:6767"
    depends_on:
      keycloak:
        condition: service_started
      timescaledb:
        condition: service_healthy
    restart: 
      unless-stopped
    env_file:
    - .env.dynamic-frcm
    - .env.keycloak
    - .env.timescale
    - .env.frcm-api


  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend_keycloak:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3333:3000"
    environment:
      HOST: 0.0.0.0
    command: sh -lc "npm install && npm start"
    restart: 
      unless-stopped
    depends_on:
      frcm-api:
        condition: service_started
      keycloak:
        condition: service_started
    env_file:
      - .env.frontend





volumes:
  frontend_node_modules:
  postgres_data:
  timescale_data:


networks:
  default:
    driver: bridge
