services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3333:3000"
    environment:
      HOST: 0.0.0.0
    command: sh -lc "npm install && npm start"
    restart: 
      unless-stopped

  postgres:    
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: 
      unless-stopped

  timescaledb: 
    image: timescale/timescaledb:latest-pg16 
    container_name: timescale-db
    environment:
      - POSTGRES_USER=${TIMESCALE_USER}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD}
      - POSTGRES_DB=${TIMESCALE_DATABASE}
    ports: 
      - "${TIMESCALE_PORT}:5432"
    volumes: 
      - timescale_data:/var/lib/postgresql/data 
      - ./init-timescaledb:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALE_USER} -d ${TIMESCALE_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: 
      unless-stopped
  

  frcm-api:
    build: .
    container_name: frcm-api
    ports:
      - "4444:8000"
    depends_on:
      postgres:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
    restart: 
      unless-stopped
    env_file:
    - .env.postgres
    - .env.timescale






volumes:
  frontend_node_modules:
  postgres_data:
  timescale_data:


networks:
  default:
    driver: bridge
