services:


  postgres:
    image: postgres:17
    container_name: postgres
    restart: 
      unless-stopped
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Use "start" for production mode, "start-dev" for development/testing
      KC_HOSTNAME: ${KC_HOST}
    ports:
      - "8080:8080"
    command: start-dev # Change to 'start' for production
    depends_on:
      - postgres

  mailhog:
    depends_on:
      - keycloak
    image: mailhog/mailhog
    container_name: keycloak_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped




  timescaledb:
    image: timescale/timescaledb:latest-pg16 
    container_name: timescaledb
    environment:
      - POSTGRES_USER=${TIMESCALE_USER}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD}
      - POSTGRES_DB=${TIMESCALE_DATABASE}
    ports: 
      - "5468:5432"
    volumes: 
      - timescale_data:/var/lib/postgresql/data 
      - ./init-timescaledb:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALE_USER} -d ${TIMESCALE_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: 
      unless-stopped
  

  frcm-api:
    build: .
    container_name: frcm-api
    ports:
      - "6767:6767"
      - "8090:8080" # for keycloak testing
    depends_on:
      keycloak:
        condition: service_started
      timescaledb:
        condition: service_healthy
    restart: 
      unless-stopped
    env_file:
    - .env.dynamic-frcm
    - .env.keycloak
    - .env.timescale
    - .env.frcm-api


  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend_keycloak:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3333:3000"
    environment:
      HOST: 0.0.0.0
    command: sh -lc "npm install && npm start"
    restart: 
      unless-stopped
    depends_on:
      frcm-api:
        condition: service_started
      keycloak:
        condition: service_started
    env_file:
      - .env.frontend





volumes:
  frontend_node_modules:
  postgres_data:
  timescale_data:


networks:
  default:
    driver: bridge
