services:


  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5467:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
  

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    environment:
      KEYCLOAK_ADMIN: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}

      # DB (Postgres)
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      # Behind nginx with forwarded headers
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"

      # Public URL (VM example). For local dev use https://localhost:8443 etc.
      KC_HOSTNAME: https://${KC_PUBLIC_IP_ADDRESS}:${KC_PUBLIC_PORT}
      KC_HOSTNAME_ADMIN: https://${KC_PUBLIC_IP_ADDRESS}:${KC_PUBLIC_PORT}

      KC_HOSTNAME_STRICT: "false"
      KC_LOG_LEVEL: info
    command: ["start-dev"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    


  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - ${NGINX_ACCESS_PORT}:443
    depends_on:
      keycloak:
        condition: service_started
    restart: unless-stopped






  mailhog:
    depends_on:
      - keycloak
    image: mailhog/mailhog
    container_name: keycloak_mailhog
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_HTTP_PORT}:8025"
    restart: unless-stopped




  timescaledb:
    image: timescale/timescaledb:latest-pg16 
    container_name: timescaledb
    environment:
      - POSTGRES_USER=${TIMESCALE_USER}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD}
      - POSTGRES_DB=${TIMESCALE_DATABASE}
    ports: 
      - "5468:5432"
    volumes: 
      - timescale_data:/var/lib/postgresql/data 
      - ./init-timescaledb:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALE_USER} -d ${TIMESCALE_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: 
      unless-stopped
  

  frcm-api:
    build: .
    container_name: frcm-api
    ports:
      - "6767:6767"
    depends_on:
      keycloak:
        condition: service_started
      timescaledb:
        condition: service_healthy
    restart: 
      unless-stopped
    env_file:
    - .env


  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend_keycloak:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5555:5000"
    environment:
      HOST: 0.0.0.0
      PORT: 5000
    command: sh -lc "npm install && npm start"
    restart: 
      unless-stopped
    depends_on:
      frcm-api:
        condition: service_started
      keycloak:
        condition: service_started
    env_file:
      - .env





volumes:
  frontend_node_modules:
  postgres_data:
  timescale_data:


networks:
  default:
    driver: bridge

